### ISSUE TITLE
[Suggestion] Add option to revert inactive portal overlay

### ISSUE THREAD

**Issue by Toastman30001** [DatBear/Guardians-of-the-Rift-Helper#43]
Add an option to revert the inactive portal overlay change to how it was before. I found the timer being in the small infobox much better to read instead of adding stuff to the already big overlay.

**Comment by Unmoon** [comment]
I liked the earlier display, as it had colors to sort of notify that portal was spawning soon.

**Comment by Yookes** [comment]
i also liked the earlier display, can it please be reverted? or maybe a setting so you can toggle between both?

**Comment by netstormuk** [comment]
I am so confused, what happened to the timer to the start of the game in the middle info box, no idea when stuff is ready now

**Comment by MirrorImageQS** [comment]
Yeah, I have to agree. If this is referring to the changes from #42, all of the changes feel like a negative change to me.

- Moving all of the timers into the OSRS UI instead of RuneLite infoboxes means they can no longer be moved around (I had all of my details in the bottom-middle before - now it's all locked to the top-left)
- Using the OSRS UI means the color-coding of the timers no longer applies. So there's no longer the visible warning when a portal is approaching or for the round start.
- The OSRS UI for this has harder to read text because there's no background to it, unlike RuneLite infoboxes.
- This new version does not have a working round-start timer on your first round, unlike the old version. That especially made it very confusing on my very first round using this new version because everything now just looked broken (for lack of a blatant changelog explaining the changes - I'm only aware of these changes because I was coming here to report everything being broken).
- Your Readme is now out of sync with the plugin, re: `Overlay panel shows: Time since last portal, time until next game, and reward points` -  those first two are now invalid.

Altogether, while using the OSRS UI might look more "natural", it also has far more usability issues that RuneLite solves, which makes it a weird choice to forego using RuneLite's functions.

**Comment by shirosora1** [comment]
The grey portal is half-way down my screen sometimes and it can't be moved. Also I've missed portals since this update because I have no idea when they're about to spawn anymore. The previous visual timer going red was one of the best features and it fitting nicely into the box meant less screen clutter. This plug-in made the minigame so much nicer but the things that did are now gone? I wish it was possible to revert back.

**Comment by camschnackel** [comment]
This jarring change had me convinced that the plugin was actually broken. Spent 20 minutes messing with settings, restarting client, uninstalling/reinstalling plugin, etc. Please add an option to revert for the reasons other's have stated above.

**Comment by DatBear** [comment]
This will be live when the PR [here](https://github.com/runelite/plugin-hub/pull/3962) gets merged in - sorry, didn't think this would affect people so negatively!

**Comment by Toastman30001** [comment]
> This will be live when the PR [here](https://github.com/runelite/plugin-hub/pull/3962) gets merged in - sorry, didn't think this would affect people so negatively!

great, thanks!
